name = input("What is your name? ")
number = input("What is your student number? ")
year = input("What year are you on? ")
print("Name: " + name)
print("Student number: " + number)
print("Year: " + year)